== Camel Spring Boot Microsoft Exchange IMAP Oauth2 Authentication

This is an example that shows how to use Camel on Spring Boot to connect with
IMAP protocol and access email data for Office 365 users using OAuth2 authentication.

The application will use the client credentials grant flow to get the access token
and use it to authenticate IMAP connections.


=== Prerequisite

* To use OAuth, an application must be registered with Azure Active Directory.
Follow the instructions listed in https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app[Register an application with the Microsoft identity platform] to register a new application.

* Enable application to access Exchange mailboxes via client credentials flow adding *IMAP.AccessAsApp* permission. Instructions https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#add-the-pop-and-imap-permissions-to-your-aad-application[here]

* Create and register your Azure Active Directory application's service principal
in Exchange via Exchange Online PowerShell. Instructions https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#register-service-principals-in-exchange[here]

* Edit the link:src/main/resources/application.properties[application.properties] adding the values to the properties marked with ``<FILL-ME>`` tag

=== How to run

You can run this example using:

[source%nowrap, console]
----
mvn spring-boot:run
----
And you should see this output:

[source%nowrap, console]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.13)

18:43:42.310 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.23.Final-redhat-00001
18:43:42.310 [main] INFO  io.fabric8.quickstarts.Application - Starting Application using Java 1.8.0_345 on localhost with PID 3388696 (/home/xxxxx/spring-boot-camel-mail-exchange-oauth2-imap/target/classes started by xxxx in /home/xxxxx/spring-boot-camel-mail-exchange-oauth2-imap)
18:43:42.312 [main] INFO  io.fabric8.quickstarts.Application - No active profile set, falling back to 1 default profile: "default"
18:43:43.108 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.apache.camel.spring.boot.CamelAutoConfiguration' of type [org.apache.camel.spring.boot.CamelAutoConfiguration$$EnhancerBySpringCGLIB$$70ceedc5] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
18:43:43.355 [main] INFO  o.a.c.i.c.DefaultTypeConverter - Type converters loaded (core: 195, classpath: 5)
18:43:43.631 [main] INFO  o.a.c.spring.boot.RoutesCollector - Loading additional Camel XML routes from: classpath:camel/*.xml
18:43:43.632 [main] INFO  o.a.c.spring.boot.RoutesCollector - Loading additional Camel XML rests from: classpath:camel-rest/*.xml
18:43:43.637 [main] INFO  o.a.camel.spring.SpringCamelContext - Apache Camel 2.23.2.fuse-7_11_1-00009-redhat-00001 (CamelContext: CamelMailExchangeOAuth2) is starting
18:43:43.638 [main] INFO  o.a.c.m.ManagedManagementStrategy - JMX is enabled
18:43:43.783 [main] INFO  o.a.camel.spring.SpringCamelContext - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
18:43:43.805 [main] INFO  o.a.c.spring.boot.RoutesCollector - Starting CamelMainRunController to ensure the main thread keeps running
18:43:43.818 [main] INFO  o.a.camel.spring.SpringCamelContext - Route: camel-mail-ms-exchange started and consuming from: imaps://outlook.office365.com:993?bridgeErrorHandler=true&debugMode=true&delay=5000&delete=false&session=%23mailSession
18:43:43.819 [main] INFO  o.a.camel.spring.SpringCamelContext - Total 1 routes, of which 1 are started
18:43:43.821 [main] INFO  o.a.camel.spring.SpringCamelContext - Apache Camel 2.23.2.fuse-7_11_1-00009-redhat-00001 (CamelContext: CamelMailExchangeOAuth2) started in 0.182 seconds
18:43:43.823 [main] INFO  io.fabric8.quickstarts.Application - Started Application in 1.795 seconds (JVM running for 2.176)

18:54:57.910 [Camel (CamelMailExchangeOAuth2) thread #2 - imaps://outlook.office365.com:993] INFO  camel-mail-ms-exchange - message Received:
From: John Doe <jdoe@example.com>
Subj: Test
Body:
This is a Test!!!

18:54:58.354 [Camel (CamelMailExchangeOAuth2) thread #2 - imaps://outlook.office365.com:993] INFO  camel-mail-ms-exchange - message Received:
From: Teigan Moore <teigan@xyz.com>
Subj: Prova
Body:
Prova Prova Prova
--
Teigan Moore
----